spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: raissamich12@gmail.com
    url: jdbc:postgresql://localhost:5432/User
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true